DROP TABLE IF EXISTS RES_DEPARTMENT;
CREATE TABLE RES_DEPARTMENT
(
   ID          		BIGINT NOT NULL,
   NAME				VARCHAR(100) NOT NULL,
   PARENT_DEP_ID    BIGINT,
   MANAGER_ID		BIGINT,
   LOCATION         VARCHAR(100),  
   OPEN_PERSITIONS	INT NOT NULL,
   PATH				VARCHAR(1024),
   VERSION			BIGINT,
   PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS RES_EMPLOYEE;
CREATE TABLE RES_EMPLOYEE
(
   ID          		BIGINT NOT NULL,
   DEP_ID    		BIGINT NOT NULL,
   FIRST_NAME       VARCHAR(20) NOT NULL,
   LAST_NAME        VARCHAR(100) NOT NULL,
   LDAP_USER_NAME   VARCHAR(100) NOT NULL,
   GENDER		    CHAR(1),
   BIRTHDAY         DATETIME,
   TITLE			VARCHAR(100) NOT NULL,
   GRADE			VARCHAR(20) NOT NULL,
   VERSION			BIGINT,
   PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;